{% set name = "pdfminer-six" %}
{% set version = "20250416" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 30956a85f9d0add806a4e460ed0d67c2b6a48b53323c7ac87de23174596d3acd
  patches:
    - patch.diff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning <3
    - pip
  run:
    - python >={{ python_min }}
    - charset-normalizer >=2.0.0
    - cryptography >=36.0.0

test:
  imports:
    - pdfminer
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pdfminer/pdfminer.six
  summary: PDF parser and analyzer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
