{% set name = "pdfminer-six" %}
{% set version = "20250324" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdfminer.six-{{ version }}.tar.gz
  sha256: 1ac8703a5ec12e37de06e3f9a45051635c7c65e32aca99935ad44250fc56ea78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning <3
    - pip
  run:
    - python >={{ python_min }}
    - charset-normalizer >=2.0.0
    - cryptography >=36.0.0

test:
  imports:
    - pdfminer
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pdfminer/pdfminer.six
  summary: PDF parser and analyzer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
